name: GitHub Actions
run-name: ${{ github.actor }} is running ${{ github.workflow }}
on: 
  push:
    branches: 
    - "main"
    - "docker-image"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install frontend
        run: |
          cd ulearn
          npm install
  
      - name: Install backend
        run: |
          cd ulearn/server
          npm install
      
      - name: Log in to Docker Hub
        run: |
          echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image      
        run: |
          docker build -t your_dockerhub_username/your_image_name:${{ github.sha }} .
          docker push your_dockerhub_username/your_image_name:${{ github.sha }}
