name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v4
      
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ulearn
        password: aaammulearn
        
    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_TAG: latest
      run: |
        docker build -t #insert name here :${DOCKER_IMAGE_TAG} .
        docker push #insert name here :${DOCKER_IMAGE_TAG}
